spring:
  application:
    name: meli-api
  webflux:
    base-path: /

server:
  port: 8080

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  webjars:
    prefix: /webjars

# Logging Configuration
logging:
  level:
    root: INFO
    meli.jestebandev: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

